### ISSUE TITLE
[proposal] npx support

### ISSUE THREAD

**Issue by knilink** [jfcherng/copilot-node-server#17]
it's be great to support running with npx like just `npx copilot-node-server --stdio`
adding
```
  "bin":{
    "copilot-node-server":"copilot/dist/language-server.js"
  },
```
to package.json should do the job

**Comment by jfcherng** [comment]
LGTM. Would you like to make a PR?

**Comment by jfcherng** [comment]
Thanks. Added in https://github.com/jfcherng/copilot-node-server/commit/a4a18ba57b6a21c416c60b6037e46c177529ac10 but I would like to keep the tag with upstream so this is only available when the upstream has a new version.

**Comment by jfcherng** [comment]
v1.41.0 has been released with this change.
