### ISSUE TITLE
Adding a package-lock.json

### ISSUE THREAD

**Issue by DamienCassou** [jfcherng/copilot-node-server#19]
Would it be possible to commit a package-lock.json? This makes things easier for packagers and ease reproducibility.

**Comment by jfcherng** [comment]
Sorry I don't understand. Here is no package dependency in this repository.

**Comment by DamienCassou** [comment]
@jfcherng indeed. Regardless of the number of dependencies, some packaging systems want a lock file. This is why my PR adding copilot-node-server to nixpgks adds a fake lock file: https://github.com/NixOS/nixpkgs/pull/348771.

**Comment by jfcherng** [comment]
uh so what it will look like, an empty one?

**Comment by DamienCassou** [comment]
I don't really care about credit but I love contributing :-).

https://github.com/jfcherng/copilot-node-server/pull/20
